### ISSUE TITLE
internalModel instead of model defined in form.key and schema

### ISSUE THREAD

**Issue by ragsnas** [OptimalBPM/angular-schema-form-dynamic-select#20]
i am using your addon to display a `ui-select-multiple`.
It is displayed correctly, loads the data remotely and i can select and unselect entries.

But it doesn't change the underlying ng-model.

When i inspect the element, i see that it uses "internalModel" as ng-model in the ui-select-container.

Unlike in [your example](http://plnkr.co/edit/juqoNOt1z1Gb349XabQ2?p=preview), where it is the actual model (`multipleDemo.colors`).

What could be the reason?
Here is my config:

```
schema: { groups: {type: "array", items:{ type: "string"} } } };
form: {
  key: "groups", 
  type: "uiselectmultiple",
  options: {
    multiple: true, 
    httpGet: {
      url: "/taggroups/api?all"
   },
   map: {
      valueProperty: "id",
      nameProperty: "name"
  }
}
```

**Comment by nicklasb** [comment]
Hi, 
Yes, the inner workings of UI-select is a little bit strange, and therefore the ASDFS wrapper (or really the implementation that Chengz did), turned out a bit strange, too. There was a couple of some reasons to use an internal model at the time. Even though I can't even remember one right now. :-)

I was however under the impression that the underlying model was changed through the on-select event when I tested it, that might have stopped working.

The UI-select implementation is something I have wanted to fix properly for a while now, I just created a "ui-select" feature branch to try and make it work. Also @ngpatel143 is working with this now, I believe. 

(That is not my example, that is UI-selects own example, [my demo is here](http://demo.optimalbpm.se/angular-schema-form-dynamic-select/)  )

**Comment by nicklasb** [comment]
Actually, in [my demo](http://demo.optimalbpm.se/angular-schema-form-dynamic-select/) , the underlying model _is changed_ for ui-multiselect.

**Comment by nicklasb** [comment]
Or have I misunderstood something?

**Comment by ragsnas** [comment]
No, it is changing in the demo.
The problem i have is that it is not initialized right.
When selected, it changes the underlying model, yet it assumes that model to be an array of ids rather than a model.

If first my model is:

```
$scope.myModel.tags = [{id: 1, name: "javascript"}, {id: 2, name: "ecma"}]
```

Then after selecting a new tag (having id: 5 and name: "foo") and the tag "ecma" again, the model is:

```
$scope.myModel.tags = [{id: 1, name: "javascript"}, {id: 2, name: "ecma"}, 5, 2]
```

I tried to change the way the model is set in the first place but that somehow seems wrong because tags should be a set of objects.
So the problem is with the initial setting of the pre-selected elements and with the selecting of objects in general.

At first i thought the problem is the internalModel.

**Comment by ragsnas** [comment]
Are there any Events that i could listen to to change the incoming data for the model and the outcoming model data?
Then i'd be fine with the component working with id arrays i guess.

**Comment by nicklasb** [comment]
1. Well, that is the way ASFDS works. It works by id fields:s; or value/name combination. 
   Working directly with model values, like the original UI-select does for some strange reason, has basically no use cases, it is always identifiers one uses in these cases.
2. I am not sure at what stage you want to intercept the data. Either way, I would strongly advice you to always work with Id:s referencing the data instead of actual instances. What happens if you want to change that instance? You would have to find all the copies and change everywhere? But if you still want to, use the model as the id, I guess that could work.

**Comment by nicklasb** [comment]
Did it work out for you?

**Comment by ragsnas** [comment]
I changed my API to deliver the selection as an array of id's, yet still the element doesn't show the selected values.
So the underlying model has `groups: [1 , 5, 7]` but the elements still does not show it.

I can select a new value and it is shown and it is stored in the internal model and later overwrites the actual model but the actual model is not used to initially set a state.

**Comment by nicklasb** [comment]
Hm. Strange. 
Then the only thing remaining now is to make a simple plunkr example that acts like this, then I can debug my way to the problem. You do not have to use an API or anything, just hard code when needed.

**Comment by ragsnas** [comment]
I will next week. Thanks anyway.

**Comment by nicklasb** [comment]
Just a thought, if you select the same groups,  does the underlying model end up with _exactly_ `groups: [1 , 5, 7]`? I am thinking that the model values perhaps doesn't exactly match the values in the drop down? You know like [1 , 5, 7] != ["1" , "5", "7"]?

**Comment by nicklasb** [comment]
@ragsnas : 
You are right, I have now recreated it in the example. It seems that sometimes(perhaps integers) are ignored for some strange reason.

I'll be back with a fix shortly, thanks for the heads up!

**Comment by nicklasb** [comment]
Update: 
It has to do with callbacks, it seems that the internal model is initiated before the callbacks have returned. 

Just a tip: In this case, you would probably have found the problem yourself pretty quickly had you had an example to try with. 

To help out, someday I'll put up a plunkr-version of the example for people to play around with.

**Comment by nicklasb** [comment]
Hi, this bug is now fixed in the develop branch.

**Comment by ragsnas** [comment]
Hey,

i made a plunkr but i have problems with the dependencies:
http://plnkr.co/edit/SiiO7nUF5E1JTbETFfm1?p=preview

As mentioned in another issue ticket the documentation seems to be wrong.
For starters, ng-translate is mentioned to be installed via bower yet the "make sure you have these included" doesn't mention it.

So i'm getting a `[$injector:modulerr]` Error.

I will add an actual fake API to the plunkr later.

**Comment by nicklasb** [comment]
I'll take a look!

**Comment by nicklasb** [comment]
You seem to have a different objectpath.js than I do. Not sure what that one is, it is not any version in bower, either.
Anyway, use this, and then the injection issue goes away:
https://github.com/mike-marcacci/objectpath/blob/master/lib/ObjectPath.js

**Comment by nicklasb** [comment]
WRT ng-translate, it is currently not used all over the component, but will be, so I left it there.

**Comment by nicklasb** [comment]
@ragsnas : Did it work out for you? Can I close this?

**Comment by nicklasb** [comment]
Closing; please open if you need to.
