### ISSUE TITLE
Set selected option

### ISSUE THREAD

**Issue by a58az** [OptimalBPM/angular-schema-form-dynamic-select#48]
Hello, how can I dynamically set selected option?

**Comment by nicklasb** [comment]
It doesn't work to set the model value?

**Comment by a58az** [comment]
It doesn't work, maybe problem that I use httpGet method to get data?

**Comment by nicklasb** [comment]
No, the selection is not related to the population, was it strapselect or
UI-select?

**Comment by nicklasb** [comment]
OK, so I have checked with the example. 
Setting the model `model["fieldname"] ="value1";` directly works with the strapselects. 

It does not, however, work with UI-select. 
This because the UI-select way of doing things is to sort of have the model in the titleMap(which I find extremely cumbersome).

So, for example, to set the ui-select-value in the example, I add a button that calls this function:

``` js
    $scope.test = function () {
        $scope.form[2].options.scope.select_model.selected = {"name":"text2", "value": "value2" };
    }
```

For a UI-multi-select it is a little bit different:

```
$scope.test = function () {
    $scope.form[3].options.scope.internalModel = [{"name":"text2", "value": "value2" }];
}
```

**Comment by nicklasb** [comment]
So this means  that the multiple and single ui-selects doesn't work in the exact same way. 
I will have to take a look at that. for example I will rename the insideModel in the single ui-select to internalModel. Strange that they ever been different.

**Comment by nicklasb** [comment]
Haven't gotten any further response, closing.

**Comment by LeonardoGentile** [comment]
was this improved somehow or is still uncertain?

**Comment by nicklasb** [comment]
Well, they are very different. It is kind of hard to hide that.
